# Pandas入門

**Pandasとは？**<br>
読み方は「パンダス」です。Pandasとは、データ操作を高速かつ効率的に扱う「データフレーム形式」を用いて、データ解析を支援する機能を提供するPythonのライブラリとなります。データを扱う言語として「SQL」もありますが、PandasはSQLと似たような感覚でデータの処理が出来ます。SQLに加えて、Pandasは膨大なデータの分析や処理が非常に効率よくシンプルに行えるメリットがあります。膨大なデータをストレスなく分析・処理することは、機械学習エンジニアにとって初歩的かつ必須のスキルです。


**なぜPandasを学ぶのか？**<br>
機械学習において、データセットを解析・処理を行うのは必須の工程となります。その工程を効率的に行うのに、Pandasを使うことが標準となっているため、初級機械学習エンジニアにとってPandasをストレス無く使うことは必要なスキルとなります。また、Pandasと密接な関係にある機械学習のライブラリーも多数存在します。例えば、機械学習で必須ライブラリー「Numpy（科学的数値計算ライブラリ）」ですが、Pandasとセットで使われます。機械学習エンジニアの核は「データセット」であり、Pandaσの使い方をマスターすることで、必要な処理や分析を効率的に行えるようになりましょう。

# Pandasの基本的な概要
Pandasの基本的な概要をみていきましょう。

* Numpyとはデータ解析を支援する機能を提供するPythonライブラリ
* データ操作のための高速で効率的なデータフレーム（DataFrame）オブジェクトを使用
* 行（Row)が横で列（Column)が縦
* import pandas as pd Pandasをpdとしてインポート
* DataFrame.columns データフレームのカラム情報
* DataFrame.index データフレームのインデックス情報
* 基本的な操作のみ覚えて必要に応じて公式ドキュメントを利用

In [1]:
# import pandas as pd Pandasをpdとしてインポート
import numpy as np
import pandas as pd

In [3]:
body = np.array([[182,169,190,178,176],[81,59,87,72,79]])
body

array([[182, 169, 190, 178, 176],
       [ 81,  59,  87,  72,  79]])

In [4]:
df = pd.DataFrame(body)
df

     0    1    2    3    4
0  182  169  190  178  176
1   81   59   87   72   79

In [5]:
type(body)

numpy.ndarray

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
# DataFrame.columns データフレームのカラム情報
df.columns = ['Jun', 'Taka', 'Testu', 'Ken', 'Kazu']

In [8]:
df

   Jun  Taka  Testu  Ken  Kazu
0  182   169    190  178   176
1   81    59     87   72    79

In [9]:
# DataFrame.index データフレームのインデックス情報
df.index = ["Height", "Weight"]

In [10]:
df

        Jun  Taka  Testu  Ken  Kazu
Height  182   169    190  178   176
Weight   81    59     87   72    79

In [12]:
# columnsの変更
df = df.rename(columns={'Jun' : 'Hikaru'})

In [13]:
df

        Hikaru  Taka  Testu  Ken  Kazu
Height     182   169    190  178   176
Weight      81    59     87   72    79

# Pandasの基本的なデータフレームの構造と、特定の行や列の要素のアクセスの仕方
Pandasの基本的なデータフレームの構造と、特定の行や列の要素のアクセスの仕方を見ていきましょう。

* pd.DataFrame() データフレームの作成
* DataFrame.index データフレームのインデックス情報
* DataFrame.shape データフレームのサイズ（行列のサイズ）
* DataFrame.describe() 基本統計量の確認
* DataFrame.astype() dtype（データ型）の指定
* DataFrame.info() データフレームのサマリー（要約情報）
* DataFrame['A'] 列「A」の要素
* DataFrame.A 同様に列「A」の要素
* DataFrame.loc[:, ['A']] 全ての行の列「A」の要素
* DataFrame.loc['Math',['A','C']] 行「Math」と列「A」「C」の要素
* DataFrame.iloc[0] 行「0」の要素
* DataFrame.iloc[1] 行「1」の要素
* DataFrame.iloc[:, 0:3] 全ての行の列「0〜2」までの要素
* DataFrame.iloc[0, 0:4] 行「０」の列「0〜3」までの要素
* locとilocは混乱しがちですので間違えなく覚えましょう
* locはラベル名を指定、ilocは行列番号を指定

In [17]:
# pd.DataFrame() データフレームの作成, DataFrame.columns データフレームのカラム情報, DataFrame.index データフレームのインデックス情報
df = pd.DataFrame(data=[['81', '100', '69', '78', '95'],['70', '93', '71', '82', '89']], columns=['A', 'B', 'C', 'D', 'E'], index=['Math', 'English'])

In [20]:
df

          A    B   C   D   E
Math     81  100  69  78  95
English  70   93  71  82  89

In [21]:
type(df)

pandas.core.frame.DataFrame

In [24]:
# DataFrame.shape データフレームのサイズ（行列のサイズ）
df.shape

(2, 5)

In [26]:
# DataFrame.info() データフレームのサマリー（要約情報）
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Math to English
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      object
 1   B       2 non-null      object
 2   C       2 non-null      object
 3   D       2 non-null      object
 4   E       2 non-null      object
dtypes: object(5)
memory usage: 204.0+ bytes

In [27]:
# DataFrame.astype() dtype（データ型）の指定
df = df.astype(int)
df

          A    B   C   D   E
Math     81  100  69  78  95
English  70   93  71  82  89

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Math to English
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
 2   C       2 non-null      int64
 3   D       2 non-null      int64
 4   E       2 non-null      int64
dtypes: int64(5)
memory usage: 204.0+ bytes

In [29]:
# DataFrame.describe() 基本統計量の確認
df.describe()

               A           B          C          D          E
count   2.000000    2.000000   2.000000   2.000000   2.000000
mean   75.500000   96.500000  70.000000  80.000000  92.000000
std     7.778175    4.949747   1.414214   2.828427   4.242641
min    70.000000   93.000000  69.000000  78.000000  89.000000
25%    72.750000   94.750000  69.500000  79.000000  90.500000
50%    75.500000   96.500000  70.000000  80.000000  92.000000
75%    78.250000   98.250000  70.500000  81.000000  93.500000
max    81.000000  100.000000  71.000000  82.000000  95.000000

In [30]:
# DataFrame['A'] 列「A」の要素
df['A']

Math       81
English    70
Name: A, dtype: int64

In [32]:
type(df['A'])

pandas.core.series.Series

In [33]:
# DataFrame.A 同様に列「A」の要素
df.A

Math       81
English    70
Name: A, dtype: int64

In [34]:
# DataFrame.loc[:, ['A']] 全ての行の列「A」の要素
df.loc[:,['A']]

          A
Math     81
English  70

In [35]:
# DataFrame.loc['Math',['A','C']] 行「Math」と列「A」「C」の要素
df.loc['Math', ['A', 'C']]

A    81
C    69
Name: Math, dtype: int64

In [37]:
# DataFrame.iloc[0] 行「0」の要素
df.iloc[0]

A     81
B    100
C     69
D     78
E     95
Name: Math, dtype: int64

In [38]:
# DataFrame.iloc[1] 行「1」の要素
df.iloc[1]

A    70
B    93
C    71
D    82
E    89
Name: English, dtype: int64

In [40]:
# DataFrame.iloc[:, 0:3] 全ての行の列「0〜2」までの要素
df.iloc[:, 0:3]

          A    B   C
Math     81  100  69
English  70   93  71

In [41]:
df.iloc[0, 0]

81

In [42]:
# DataFrame.iloc[0, 0:4] 行「０」の列「0〜3」までの要素
df.iloc[0, 0:4]

A     81
B    100
C     69
D     78
Name: Math, dtype: int64

# csvファイルからデータの読み込み
Pandasを使ってcsvファイルからデータの読み込みと、読み込んだデータの紐解きを行なっていきましょう。本チャプターでは、下記の2つのCSVファイルを動画内で使用します。

* pd.read_csv() CSVデータからデータフレームの作成
* DataFrame.head() データフレームの最初の5行を表示（デフォルト）
* DataFrame.tail() データフレームの最後の5行を表示（デフォルト）
* DataFrame['A'] 列「A」の要素へアクセス
* DataFrame.corr() 各項目の相関係数
* DataFrame.groupby() グルーピングによるデータの集計

In [47]:
# pd.read_csv() CSVデータからデータフレームの作成
# Google Colab内に指定のファイルをアップしてから実行します
df = pd.read_csv('data1.csv')

In [48]:
# DataFrame.head() データフレームの最初の5行を表示（デフォルト）
df.head()

   0.563823406  0.926037583  0.564529862
0     0.226930     0.774618     0.415330
1     0.993598     0.030036     0.210686
2     0.355566     0.824691     0.629814
3     0.784904     0.614295     0.127989
4     0.442514     0.163834     0.088494

In [51]:
# ヘッダーがないのでヘッダー無しと指定
df = pd.read_csv('data1.csv', header=None)
df.head()

          0         1         2
0  0.563823  0.926038  0.564530
1  0.226930  0.774618  0.415330
2  0.993598  0.030036  0.210686
3  0.355566  0.824691  0.629814
4  0.784904  0.614295  0.127989

In [52]:
type(df)

pandas.core.frame.DataFrame

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB

In [55]:
df.describe()

                0           1           2
count  100.000000  100.000000  100.000000
mean     0.460883    0.487668    0.507878
std      0.278284    0.306104    0.295137
min      0.008179    0.005217    0.012975
25%      0.221251    0.209450    0.202979
50%      0.428495    0.455401    0.548508
75%      0.700257    0.761196    0.808566
max      0.994047    0.999703    0.980560

In [58]:
# data2の読み込み
df2 = pd.read_csv('data2.csv')
df2.head()

  Employee ID  Evaluation  Promotion Salary in JPY (Date:2001-2017)  Quit
0         565         0.1        1.0                            Low   1.0
1         141         0.1        0.0                            Low   1.0
2         786         0.6        1.0                            Low   0.0
3        1770         1.0        1.0                            Low   0.0
4         662         1.0        0.0                            Low   0.0

In [60]:
df2.shape

(201, 5)

In [61]:
# DataFrame.tail() データフレームの最後の5行を表示（デフォルト）
df2.tail()

,Employee ID,Evaluation,Promotion,Salary in JPY (Date:2001-2017),Quit
196,596,0.2,0.0,Mid,0.0
197,1729,0.1,0.0,Mid,0.0
198,1137,1.0,1.0,Mid,0.0
199,NaN,NaN,NaN,NaN,1.0
200,"All employees data is collected annonimously, ...",NaN,NaN,NaN,NaN

In [62]:
# フッターを読み込まない
df2 = pd.read_csv('data2.csv', skipfooter=2, engine="python")
df2.tail()

     Employee ID  Evaluation  Promotion Salary in JPY (Date:2001-2017)  Quit
194          766         1.0          0                            Mid     1
195         2350         0.0          0                            Mid     1
196          596         0.2          0                            Mid     0
197         1729         0.1          0                            Mid     0
198         1137         1.0          1                            Mid     0

In [63]:
# カラム名を確認
df2.columns

Index(['Employee ID', 'Evaluation', 'Promotion',
       'Salary in JPY (Date:2001-2017)', 'Quit'],
      dtype='object')

In [66]:
# カラム名を変更する
df2.columns = ["ID", "Evaluation", "Promotion", "Salary", "Quit"]
df2.head()

     ID  Evaluation  Promotion Salary  Quit
0   565         0.1          1    Low     1
1   141         0.1          0    Low     1
2   786         0.6          1    Low     0
3  1770         1.0          1    Low     0
4   662         1.0          0    Low     0

In [70]:
# カラムの追加
df2['sex'] = "Male"
df2.head()

     ID  Evaluation  Promotion Salary  Quit   sex
0   565         0.1          1    Low     1  Male
1   141         0.1          0    Low     1  Male
2   786         0.6          1    Low     0  Male
3  1770         1.0          1    Low     0  Male
4   662         1.0          0    Low     0  Male

In [71]:
df2.describe()

                ID  Evaluation   Promotion        Quit
count   199.000000  199.000000  199.000000  199.000000
mean   1204.874372    0.474874    0.180905    0.547739
std     696.072589    0.322665    0.385910    0.498971
min       4.000000    0.000000    0.000000    0.000000
25%     601.500000    0.200000    0.000000    0.000000
50%    1146.000000    0.400000    0.000000    1.000000
75%    1839.500000    0.800000    0.000000    1.000000
max    2493.000000    1.000000    1.000000    1.000000

In [73]:
# DataFrame.corr() 各項目の相関係数
df2.corr()

                  ID  Evaluation  Promotion      Quit
ID          1.000000   -0.020596   0.119456 -0.118589
Evaluation -0.020596    1.000000   0.231375  0.029446
Promotion   0.119456    0.231375   1.000000 -0.228676
Quit       -0.118589    0.029446  -0.228676  1.000000

In [74]:
# DataFrame.groupby() グルーピングによるデータの集計
eva = df2.groupby('Evaluation')

In [75]:
type(eva)

pandas.core.groupby.generic.DataFrameGroupBy

In [76]:
eva.mean()

                     ID  Promotion      Quit
Evaluation
0.0         1306.666667   0.000000  0.555556
0.1         1189.466667   0.066667  0.666667
0.2         1102.656250   0.031250  0.718750
0.3         1296.157895   0.157895  0.368421
0.4         1265.230769   0.307692  0.307692
0.5         1390.692308   0.153846  0.153846
0.6         1343.294118   0.411765  0.235294
0.7         1128.300000   0.200000  0.400000
0.8          985.600000   0.333333  0.600000
0.9         1239.360000   0.280000  0.800000
1.0         1125.000000   0.187500  0.687500

# Pandas データフレームの値にアクセスして処理を行う基本的操作
* DataFrame.isnull() データフレームのNaNかどうかをBoolean型で返す
* DataFrame.isnull().isum() 値がNaNの要素の合計を確認
* DataFrame.fillna 値がNaNの要素の穴埋め

In [77]:
df3 = pd.read_csv('data3.csv')

In [78]:
df3.head()

   id  Height  Weight
0   1   152.0    84.0
1   2   152.0    75.0
2   3   152.0    81.0
3   4   152.0    76.0
4   5   152.0    61.0

In [80]:
df3.shape

(146, 3)

In [81]:
# 欠損データの確認：DataFrame.isnull() データフレームのNaNかどうかをBoolean型で返す
df3.isnull().any()

id        False
Height     True
Weight     True
dtype: bool

In [82]:
# nullの数を確認
df3.isnull().sum()

id        0
Height    9
Weight    7
dtype: int64

In [83]:
df3.head(30)

    id  Height  Weight
0    1   152.0    84.0
1    2   152.0    75.0
2    3   152.0    81.0
3    4   152.0    76.0
4    5   152.0    61.0
5    6   153.0    65.0
6    7   153.0    88.0
7    8   153.0    82.0
8    9   153.0    63.0
9   10   153.0    83.0
10  11   153.0    82.0
11  12     NaN    82.0
12  13   155.0    59.0
13  14   155.0    84.0
14  15   155.0     NaN
15  16     NaN    71.0
16  17   156.0    81.0
17  18   156.0    84.0
18  19     NaN    61.0
19  20   156.0    81.0
20  21   156.0    65.0
21  22   157.0    78.0
22  23   157.0    69.0
23  24   157.0    86.0
24  25   158.0     NaN
25  26   158.0     NaN
26  27   158.0    87.0
27  28   158.0    80.0
28  29   159.0    92.0
29  30   159.0    59.0

In [85]:
# DataFrame.fillna 値がNaNの要素の穴埋め：method=ffill: 有効な値を欠損データに使用する
df3['Height'] = df3['Height'].fillna(method='ffill')

In [86]:
df3.head(30)

    id  Height  Weight
0    1   152.0    84.0
1    2   152.0    75.0
2    3   152.0    81.0
3    4   152.0    76.0
4    5   152.0    61.0
5    6   153.0    65.0
6    7   153.0    88.0
7    8   153.0    82.0
8    9   153.0    63.0
9   10   153.0    83.0
10  11   153.0    82.0
11  12   153.0    82.0
12  13   155.0    59.0
13  14   155.0    84.0
14  15   155.0     NaN
15  16   155.0    71.0
16  17   156.0    81.0
17  18   156.0    84.0
18  19   156.0    61.0
19  20   156.0    81.0
20  21   156.0    65.0
21  22   157.0    78.0
22  23   157.0    69.0
23  24   157.0    86.0
24  25   158.0     NaN
25  26   158.0     NaN
26  27   158.0    87.0
27  28   158.0    80.0
28  29   159.0    92.0
29  30   159.0    59.0

In [87]:
df3.isnull().sum()

id        0
Height    0
Weight    7
dtype: int64

In [89]:
# 中央値で欠損データを埋める
df3['Weight'] = df3['Weight'].fillna(df3['Weight'].median())

In [90]:
df3.head(30)

    id  Height     Weight
0    1   152.0  84.000000
1    2   152.0  75.000000
2    3   152.0  81.000000
3    4   152.0  76.000000
4    5   152.0  61.000000
5    6   153.0  65.000000
6    7   153.0  88.000000
7    8   153.0  82.000000
8    9   153.0  63.000000
9   10   153.0  83.000000
10  11   153.0  82.000000
11  12   153.0  82.000000
12  13   155.0  59.000000
13  14   155.0  84.000000
14  15   155.0  75.086331
15  16   155.0  71.000000
16  17   156.0  81.000000
17  18   156.0  84.000000
18  19   156.0  61.000000
19  20   156.0  81.000000
20  21   156.0  65.000000
21  22   157.0  78.000000
22  23   157.0  69.000000
23  24   157.0  86.000000
24  25   158.0  75.086331
25  26   158.0  75.086331
26  27   158.0  87.000000
27  28   158.0  80.000000
28  29   159.0  92.000000
29  30   159.0  59.000000

In [91]:
df3.isnull().sum()

id        0
Height    0
Weight    0
dtype: int64

In [92]:
df3.describe()

               id      Height      Weight
count  146.000000  146.000000  146.000000
mean    73.500000  167.760274   75.086331
std     42.290661    9.226128   10.173991
min      1.000000  152.000000   58.000000
25%     37.250000  161.000000   66.000000
50%     73.500000  167.000000   75.086331
75%    109.750000  175.750000   84.000000
max    146.000000  185.000000   92.000000

![スクリーンショット 2022-09-14 13.05.15.png]()

In [94]:
df3['BMI1'] = df3.apply(lambda row: row['Weight'] / ((row['Height']/100)**2), axis=1)

In [95]:
df3.head()

   id  Height  Weight       BMI1
0   1   152.0    84.0  36.357341
1   2   152.0    75.0  32.461911
2   3   152.0    81.0  35.058864
3   4   152.0    76.0  32.894737
4   5   152.0    61.0  26.402355

In [96]:
def get_bmi(row):
  return row['Weight'] / ((row['Height']/100)**2)

In [97]:
df3["BMI2"] = df3.apply(get_bmi, axis=1)

In [98]:
df3.head()

   id  Height  Weight       BMI1       BMI2
0   1   152.0    84.0  36.357341  36.357341
1   2   152.0    75.0  32.461911  32.461911
2   3   152.0    81.0  35.058864  35.058864
3   4   152.0    76.0  32.894737  32.894737
4   5   152.0    61.0  26.402355  26.402355

# Pandasを使ってデータセットの結合や連結

* DataFrame.groupby() グルーピングによるデータの集計
* pd.merge() 2つのデータフレームの結合
* pd.concat() 2つのデータフレームの連結
* DataFrame.reset_index データフレームのindexを振り直す

In [104]:
df4 = pd.read_csv('data4.csv')

In [105]:
df5 = pd.read_csv('data5.csv')

In [106]:
df4.head()

   user_id    Name  Age     Sex
0        1  Yamada   32    Male
1        2  Tanaka   45    Male
2        3   Murai   29  Female
3        4   Hoshi   38    Male

In [107]:
df5.head()

   user_id  class_id  status
0        1         3       0
1        1         2       1
2        2         1       1
3        2         6       0
4        2         3       0

In [109]:
df4.shape

(4, 4)

In [110]:
df5.shape

(9, 3)

In [111]:
df4

   user_id    Name  Age     Sex
0        1  Yamada   32    Male
1        2  Tanaka   45    Male
2        3   Murai   29  Female
3        4   Hoshi   38    Male

In [112]:
df5

   user_id  class_id  status
0        1         3       0
1        1         2       1
2        2         1       1
3        2         6       0
4        2         3       0
5        3         1       0
6        3         4       1
7        3         8       1
8        4         9       1

In [113]:
# DataFrame.groupby() グルーピングによるデータの集計
user = df5.groupby('user_id')

In [114]:
user.describe()

        class_id                                                status  \
           count      mean       std  min   25%  50%   75%  max  count
user_id
1            2.0  2.500000  0.707107  2.0  2.25  2.5  2.75  3.0    2.0
2            3.0  3.333333  2.516611  1.0  2.00  3.0  4.50  6.0    3.0
3            3.0  4.333333  3.511885  1.0  2.50  4.0  6.00  8.0    3.0
4            1.0  9.000000       NaN  9.0  9.00  9.0  9.00  9.0    1.0


             mean       std  min   25%  50%   75%  max
user_id
1        0.500000  0.707107  0.0  0.25  0.5  0.75  1.0
2        0.333333  0.577350  0.0  0.00  0.0  0.50  1.0
3        0.666667  0.577350  0.0  0.50  1.0  1.00  1.0
4        1.000000       NaN  1.0  1.00  1.0  1.00  1.0

In [122]:
# pd.merge() 2つのデータフレームの結合
df6 = pd.merge(df4, df5, on='user_id')

In [123]:
df6

   user_id    Name  Age     Sex  class_id  status
0        1  Yamada   32    Male         3       0
1        1  Yamada   32    Male         2       1
2        2  Tanaka   45    Male         1       1
3        2  Tanaka   45    Male         6       0
4        2  Tanaka   45    Male         3       0
5        3   Murai   29  Female         1       0
6        3   Murai   29  Female         4       1
7        3   Murai   29  Female         8       1
8        4   Hoshi   38    Male         9       1

In [124]:
# pd.concat() 2つのデータフレームの連結: 新たなデータを作成
df7 = pd.DataFrame(data=[['5', '3', '0'], ['7', '5', '1'], ['5', '6', '2']], columns=['user_id', 'class_id', 'status'])
df7

  user_id class_id status
0       5        3      0
1       7        5      1
2       5        6      2

In [125]:
# pd.concat() 2つのデータフレームの連結
df8 = pd.concat([df6, df7])
df8

  user_id    Name   Age     Sex class_id status
0       1  Yamada  32.0    Male        3      0
1       1  Yamada  32.0    Male        2      1
2       2  Tanaka  45.0    Male        1      1
3       2  Tanaka  45.0    Male        6      0
4       2  Tanaka  45.0    Male        3      0
5       3   Murai  29.0  Female        1      0
6       3   Murai  29.0  Female        4      1
7       3   Murai  29.0  Female        8      1
8       4   Hoshi  38.0    Male        9      1
0       5     NaN   NaN     NaN        3      0
1       7     NaN   NaN     NaN        5      1
2       5     NaN   NaN     NaN        6      2

In [127]:
# DataFrame.reset_index データフレームのindexを振り直す
df8 = df8.reset_index(drop=True)
df8

   user_id    Name   Age     Sex class_id status
0        1  Yamada  32.0    Male        3      0
1        1  Yamada  32.0    Male        2      1
2        2  Tanaka  45.0    Male        1      1
3        2  Tanaka  45.0    Male        6      0
4        2  Tanaka  45.0    Male        3      0
5        3   Murai  29.0  Female        1      0
6        3   Murai  29.0  Female        4      1
7        3   Murai  29.0  Female        8      1
8        4   Hoshi  38.0    Male        9      1
9        5     NaN   NaN     NaN        3      0
10       7     NaN   NaN     NaN        5      1
11       5     NaN   NaN     NaN        6      2

# 問題

In [131]:
import numpy as np
import pandas as pd

random = np.random.randint(0,100,(5,5))
df = pd.DataFrame(random)
df.shape

(5, 5)

In [132]:
import numpy as np
import pandas as pd

random = np.random.randint(0,100,(3,3))
df = pd.DataFrame(random)
df[2]

0    86
1    95
2    47
Name: 2, dtype: int64

In [133]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(4,4))
df.loc[:,1]

0    0.942828
1   -0.206161
2   -0.039856
3   -0.098634
Name: 1, dtype: float64

In [134]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(1,50,(5,5)))
df.iloc[0:2, 4]

0    41
1    15
Name: 4, dtype: int64

In [136]:
import numpy as np
import pandas as pd

df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
dtype: int64